### ISSUE TITLE
simulator does not work

### ISSUE THREAD

**Issue by chri2** [cryptoadvance/specter-diy#189]
Hardware: rock64 (pine64): ARMv8 Processor, 4GB ram
Software: Linux rock64 4.4.190-1233-rockchip-ayufan-gd3f1be0ed310 #1 SMP Wed Aug 28 08:59:34 UTC 2019 aarch64 aarch64 aarch64 GNU/Linux
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.6 LTS"

`make unix` compiles without errors. `make simulate` finishes without errors until it tries to start `bin/micropython_unix simulate.py`.

```
rock64@rock64:~/specter-diy$ bin/micropython_unix simulate.py 
Traceback (most recent call last):
  File "simulate.py", line 7, in <module>
  File "./src/main.py", line 2, in <module>
  File "./src/specter.py", line 7, in <module>
  File "./src/platform.py", line 18, in <module>
MemoryError: memory allocation failed, allocating 1048577 bytes
```

```
rock64@rock64:~/specter-diy$ bin/micropython_unix -X heapsize=2500K simulate.py 
Traceback (most recent call last):
  File "simulate.py", line 7, in <module>
  File "./src/main.py", line 2, in <module>
  File "./src/specter.py", line 18, in <module>
  File "./src/hosts/__init__.py", line 1, in <module>
  File "./src/hosts/core.py", line 5, in <module>
  File "./src/gui/__init__.py", line 1, in <module>
  File "./src/gui/core.py", line 6, in <module>
  File "./src/gui/common.py", line 7, in <module>
  File "./src/gui/components/__init__.py", line 1, in <module>
RuntimeError: maximum recursion depth exceeded
```

Is this supposed to work?

**Comment by schnuartz-ai** [comment]
# Issue #189 — simulator does not work

**Current assessment:** LIKELY FIXED (on supported platforms; reporter self-confirmed). The original ARM-specific `MemoryError`/recursion failures from 2021 are not reproducible on the current codebase. I successfully launched the simulator on the prebuilt `bin/micropython_unix` (Linux x86_64) and it reached a running event loop. The issue appears to have been environment-specific (old ARM userland/heap config) and was self-resolved by the reporter after upgrading the OS image. No code change targeting this issue was made.

**What I investigated:**
- Full issue body + all 3 comments via `gh issue view 189`.
- Current `simulate.py`, `src/platform.py`, `src/main.py`, `src/specter.py`, `src/gui/tcp_gui.py`, `f469-disco/libs/common/asyncio/core.py`.
- Ran the prebuilt simulator in `/home/finn/specter-diy-build`.
- `git log --all` for `src/platform.py`, `simulate.py`, and grep "simulat".
- Related issue #274 (simulator segfault, Ubuntu 20.04, 2023).
- `Makefile` `simulate`/`unix` targets; `docs/simulator.md`, `docs/build.md`.

**Current code:**
- `src/platform.py:7` — `simulator = (sys.platform in ["linux", "darwin"])`.
- `src/platform.py:30` — `_PREALLOCATED = bytes(0x100000)` (exactly 1 MiB = 1048576 bytes). This is the allocation that produced the original `MemoryError: memory allocation failed, allocating 1048577 bytes` (the +1 is Micropython's object header) at the old `platform.py` line 18.
- `src/platform.py:55-114` — `SDCard` class; `src/platform.py:128` — `sdcard = SDCard(None, None)` stub for simulator (the line referenced in the task context).
- `src/main.py:46-51` — simulator uses `TCPGUI` instead of `SpecterGUI`.
- `src/gui/tcp_gui.py:13` — `TCPGUI` opens `pyb.UART('"S')` on port 8787; `src/gui/tcp_gui.py:18` — starts `tcp_loop()` task.
- `Makefile:82-83` — `simulate: unix` → `$(TARGET_DIR)/micropython_unix simulate.py`.
- `f469-disco/libs/common/asyncio/core.py:117-118` — `wait_io_event` uses `select.poll().ipoll(dt)`.

**Reproduction / validation (TESTED):**
I ran the prebuilt binary in `/home/finn/specter-diy-build` (which contains a working `bin/micropython_unix` built from the current tree):

```
$ cd /home/finn/specter-diy-build && ./bin/micropython_unix simulate.py
Running TCP-UART on 127.0.0.1 port 22849 - connect with telnet
Connect to 127.0.0.1:22849 to send QR code content
Pin None set to ON
Running TCP-UART on 127.0.0.1 port 8787 - connect with telnet
```

To rule out the `OSError: 4` I first saw (EINTR, caused by my `timeout` wrapper sending SIGTERM), I backgrounded the process and polled it: **the simulator stayed alive for 4+ seconds and was still running** when I killed it. The only stdout is the four lines above (TCP-UART on 22849, the "connect with telnet" hint, "Pin None set to ON", and TCP-UART on 8787) — i.e. it successfully imported all modules, called `display.init(False)`, mounted the SDRAM ramdisk, constructed the three hosts, constructed `TCPGUI`, called `gui.start()`, and entered `asyncio.run(self.setup())` in `src/specter.py:123`.

This is a **completely different failure mode** than the issue. The issue reported:
- `MemoryError: memory allocation failed, allocating 1048577 bytes` at `src/platform.py` line 18 — caused by `_PREALLOCATED = bytes(0x100000)` failing under the default heap on the reporter's ARMv8/rock64 with Ubuntu 18.04 (bionic).
- `RuntimeError: maximum recursion depth exceeded` at `src/gui/components/__init__.py` line 1 when running with `-X heapsize=2500K` — a secondary symptom of an undersized heap during module import.

Neither is reproducible here. The reporter's own third comment (2021-10-16) reports success after switching the rock64 to **armbian focal (bullseye)** and also confirms it works on a **Pinephone running mobian (bullseye)**; they conclude "The problem seems only to show on armv7 or armv8 running old software." No maintainer code change was made for this issue — the maintainer's only comment (2021-10-15) was "I didn't test on arm, but I think it should work."

Not tested: ARM hardware (I only have the x86_64 prebuilt binary). I cannot personally confirm the reporter's bullseye-on-rock64 result, but I have no evidence contradicting it.

**Related issues/PRs:**
- #274 (OPEN, 2023) "Segmentation fault error when starting the simulator" — Ubuntu 20.04, segfaults right after printing the same "Running TCP-UART on 127.0.0.1 port 22849" / "Pin None set to ON" lines I saw, but *before* the 8787 line. Same entry point, different failure (SIGSEGV in native code rather than Python MemoryError). Likely a distinct native/SDL/display-init crash; not the same as #189. Worth noting to anyone re-testing #189.
- #60 (CLOSED) "Buttons not working in simulator when running telnet" — simulator UX, not startup.
- #27 (CLOSED) "simulator freezes" — older.

**Implementation notes (if still relevant):**
No code change is indicated for the original ARM `MemoryError`. If the maintainers want to harden the simulator against low-heap environments, the relevant allocation is `src/platform.py:30` (`_PREALLOCATED = bytes(0x100000)`); a smaller preallocation or a try/except fallback could prevent the hard crash, but this is a low-priority robustness nicety, not a fix for a confirmed-current bug. The `OSError: 4` I observed is purely an artifact of signal-based termination (`timeout`), not a simulator bug.

**Security review:**
No security implications. The simulator path is dev-only and explicitly not a hardware-wallet trust boundary (`src/platform.py:15-17` forces `build_type = "unix"`, `bootloader_locked = False`; `src/platform.py:186-198` reports boot mode "simulator"; flash/SDRAM protection status is "not applicable" at `src/platform.py:204,223`). The `_PREALLOCATED` buffer holds uninitialized zeroed bytes for the SDRAM emulation and never touches secrets.

**Recommendation:** LIKELY FIXED — close with a note pointing to the reporter's own confirmation (armbian focal/mobian bullseye works) and #274 as the follow-up for the remaining native segfault on some Linux setups.

**Comment by Schnuartz** [comment]
Ok, will close this now. Only seems to appear on armv7 or armv8 running old software.
